# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camposReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('islabel', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('db_field', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NivelAmbito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='camposreporte',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.NivelAmbito'),
        ),
    ]
